fixtures:
  forge_modules:
    archive: 'puppet-archive'
    cron_core: 'puppetlabs-cron_core'
    inifile: 'puppetlabs-inifile'
    stdlib: 'puppetlabs-stdlib'
  symlinks:
    bitbucket: "#{source_dir}"
